version: "3.0"

services:
  backend:
    container_name: backend
    image: uni.mirkoz.homebanking-demo/backend:latest
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      DB_DRIVER: "com.mysql.jdbc.Driver"
      DB_URL: "jdbc:mysql://db:3306/pps-home-banking"
      DB_USER: "pps-home-banking"
      DB_PASS: "pps1234"
      DB_DIALECT: "org.hibernate.dialect.MySQL5InnoDBDialect"
      DB_CONSOLE: "false"
      SHOW_SQL: "true"
      UPLOAD_DIR: "/var/uploads"
    volumes:
      - ./uploads:/var/uploads
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: 'uni.mirkoz.homebanking-demo/frontend:latest'
    ports:
      - "80:80"
  db:
    container_name: db
    image: 'mysql:5.7'
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "pps-home-banking"
      MYSQL_USER: "pps-home-banking"
      MYSQL_PASSWORD: "pps1234"

