spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  jpa:
    hibernate:
      ddl-auto: create #will create schema based on entities
    show-sql: false
    database-platform: org.hibernate.dialect.${DB_DIALECT:H2Dialect}
  h2:
    console:
      enabled: ${DB_CONSOLE:true}
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

file:
  upload-dir: ${UPLOAD_DIR:/home/mirko/Desktop/uploads}