spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create} # Will create schema based on entities
    show-sql: ${SHOW_SQL:false}
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: ${DB_CONSOLE:true}
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

file:
  upload-dir: ${UPLOAD_DIR:/home/mirko/Desktop/uploads}

cron:
  interests-expression: '0 0 0 15 * ?'  # At midnight on the 15th day of every month