spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  jpa:
    hibernate:
      ddl-auto: create #will create schema based on entities
    show-sql: true
    #database-platform: org.hibernate.dialect.${DB_DIALECT:H2Dialect}
  h2:
    console:
      enabled: ${DB_CONSOLE:true}
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
